---
-
  hosts: localhost
  connection: local
  gather_facts: false
  name: "Ansible test"
  vars:
    id: "web-app"
    sec_group: "{{ id }}-sec"
    vpc_cidr: '10.0.0.0/16'
    subnet_cidr: '10.0.1.0/24'
    region: 'us-east-1'

  tasks:
    -
      ec2_vpc_net:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        cidr_block: "{{ vpc_cidr }}"
        dns_hostnames: true
        dns_support: true
        name: testVPC
        region: "{{ region }}"
        state: present
        tenancy: default
      name: "create a new ec2 VPC"
      register: ec2_vpc_net_result
    -
      ec2_vpc_subnet:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        az: us-east-1a
        cidr: "{{ subnet_cidr }}"
        map_public: true
        region: "{{ region }}"
        resource_tags:
          Name: Test
        state: present
        vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
      name: "create ec2 vpc subnet"
      register: subnet_result
    -
      ec2_vpc_igw:
        vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        state: "present"
        resource_tags:
          Name: myIGW
      name: "IGW creation"
      register: igw
    -
      ec2_vpc_route_table:
        vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
        region: "{{ region }}"
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        subnets:
          - "{{ subnet_result.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        resource_tags:
          Name: test
      name: "route table creation"
    -
      ec2_group:
        name: "{{ sec_group }}"
        description: " Sec group for App {{id}}"
        vpc_id: "{{ ec2_vpc_net_result.vpc.id }}"
        region: "{{ region }}"
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 0.0.0.0/0
            rule_desc: allow all on ssh port
      name: Create Security grup
      register: result_sec_group
    -
      ec2_key:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        name: test-key
        region: "{{ region }}"
      name: "create key pair"
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="/home/ansible/Ansible-AWS/.ssh/test-key.pem" mode=0600
      when: ec2_key_result.changed
    -
      ec2:
        assign_public_ip: true
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        count: 1
        image: ami-047a51fa27710816e
        instance_type: t2.micro
        vpc_subnet_id: "{{ subnet_result.subnet.id }}"
        key_name: test-key
        group_id: "{{ result_sec_group.group_id }}"
        region: "{{ region }}"
        wait: true
        instance_tags:
          Name: Ansible test
      name: "EC2 instance creation"
